### ISSUE TITLE
instance_create的崩MAP问题

### ISSUE THREAD

**Issue by michaelwoooo** [PandasWS/Pandas#100]
当instance_create("副本名称")时，而instance_db.txt中又没有对应的“副本名称”时，MAP直接崩掉

调试代码段
// Searching a Free Instance
	// 0 is ignored as this means "no instance" on maps
	ARR_FIND(1, MAX_INSTANCE_DATA, i, instance_data[i].state == INSTANCE_FREE);
	if( i >= MAX_INSTANCE_DATA )
		return -4;

	instance_data[i].type = db->id;
	instance_data[i].state = INSTANCE_IDLE;
	instance_data[i].owner_id = owner_id;
	instance_data[i].mode = mode;
	instance_data[i].keep_limit = 0;
	instance_data[i].keep_timer = INVALID_TIMER;
	instance_data[i].idle_limit = 0;
	instance_data[i].idle_timer = INVALID_TIMER;
	

> instance_data[i].regs.vars = i64db_alloc(DB_OPT_RELEASE_DATA);【引发了未经处理的异常:读取访问权限冲突。
> db 是 nullptr。】

	instance_data[i].regs.arrays = NULL;
	instance_data[i].cnt_map = 0;

**Comment by CairoLee** [comment]
已经修复
