### ISSUE TITLE
建议：mapflags增加限制最高伤害

### ISSUE THREAD

**Issue by michaelwoooo** [PandasWS/Pandas#101]
增加一个mapflag，限制标签地图内设定的最高伤害值

**Comment by CairoLee** [comment]
可能会用在什么场景呢？分享一下？

**Comment by michaelwoooo** [comment]
BTF的PVP&GVG。
或者特定一些任务地图
不然秒天秒地秒空气哦亲

**Comment by CairoLee** [comment]
需要区分技能和普通攻击么？

**Comment by CairoLee** [comment]
此问题已经被实现，如果还有与其相关的其他情况，可以重新打开此问题

**Comment by DepTrai92** [comment]
你们好，你们来自哪里？很难找到 华人在私服，有什么方式可以 方便聊天 或沟通？ 比如 discord skype ？ 你们使用哪一些？

**Comment by michaelwoooo** [comment]
> 你们好，你们来自哪里？很难找到 华人在私服，有什么方式可以 方便聊天 或沟通？ 比如 discord skype ？ 你们使用哪一些？

QQ：2049100
EMAIL：michaelwooo@qq.com

**Comment by CairoLee** [comment]
> 你们好，你们来自哪里？很难找到 华人在私服，有什么方式可以 方便聊天 或沟通？ 比如 discord skype ？ 你们使用哪一些？

你好~ 在中国大陆我们普遍使用 QQ 或者 微信（Wechat）~

QQ是：2602503
QQ电脑版本的下载地址是：https://im.qq.com/index.shtml

**Comment by DepTrai92** [comment]
可以要微信吗。我没有QQ

Thanks

Best Regard,
Administrator
Honor Ragnarok Online

________________________________

**Comment by CairoLee** [comment]
@DepTrai92 用 2602503 应该可以搜索到我的微信。或者留下你的微信号，我加你~
