### ISSUE TITLE
hideonnpc的问题

### ISSUE THREAD

**Issue by michaelwoooo** [PandasWS/Pandas#108]
hideonnpc不应再触发OnTouch及OnTouch_

**Comment by CairoLee** [comment]
具体描述一下表现，以及为何你觉得不应该触发？

**Comment by michaelwoooo** [comment]
Pandas\npc\re\instances\FacewormsNest.txt

`// Instance Traps :: in_face_l
//============================================================
1@face,61,132,5	script	Suspicious Mound#1	4_SOIL,5,5,{
	end;
OnTouch_:
	setarray .@num[1],
		3,2,1,3,2,1,3,2,1,3,2,1,3,2,1,
		3,2,1,3,2,1,3,2,1,3,2,1,3,2,1,
		3,2,1,3,2,1,3,2,1,3,2,1,3,2,1,
		3,2,1,3,2,1,3,2,1;
	.@npc_name$ = instance_npcname(strnpcinfo(0));
	specialeffect EF_VENOMDUST;
	disablenpc .@npc_name$;
	killmonster 'map_name$, .@npc_name$ + "::OnMyMobDead";
	getmapxy 'map_name$, .@x, .@y, BL_NPC;
	.@mon_num = .@num[atoi(strnpcinfo(2))];
	areamonster 'map_name$,.@x-1,.@y-1,.@x+1,.@y+1,"Faceworm Larva",2541,.@mon_num,.@npc_name$ + "::OnMyMobDead";
	initnpctimer;
	end;
OnTimer45000:
	enablenpc instance_npcname(strnpcinfo(0));
	stopnpctimer;
	end;
OnMyMobDead:
	end;
}`
无限经过无限触发刷怪

**Comment by michaelwoooo** [comment]
> // Instance Traps :: in_face_l
//============================================================
1@face,61,132,5	script	Suspicious Mound#1	4_SOIL,5,5,{
	end;
OnTouch_:
	setarray .@num[1],
		3,2,1,3,2,1,3,2,1,3,2,1,3,2,1,
		3,2,1,3,2,1,3,2,1,3,2,1,3,2,1,
		3,2,1,3,2,1,3,2,1,3,2,1,3,2,1,
		3,2,1,3,2,1,3,2,1;
	.@npc_name$ = instance_npcname(strnpcinfo(0));
	specialeffect EF_VENOMDUST;
	disablenpc .@npc_name$;
	killmonster 'map_name$, .@npc_name$ + "::OnMyMobDead";
	getmapxy 'map_name$, .@x, .@y, BL_NPC;
	.@mon_num = .@num[atoi(strnpcinfo(2))];
	areamonster 'map_name$,.@x-1,.@y-1,.@x+1,.@y+1,"Faceworm Larva",2541,.@mon_num,.@npc_name$ + "::OnMyMobDead";
	initnpctimer;
	end;
OnTimer45000:
	enablenpc instance_npcname(strnpcinfo(0));
	stopnpctimer;
	end;
OnMyMobDead:
	end;
}

**Comment by michaelwoooo** [comment]
要不close掉算了，仔细想想。
可能某些特定情况下也是需要hideonnpc来触发OnTouch呢
我仔细看了看rA官方的instances，都是hideonnpc和disablenpc混用的。
