### ISSUE TITLE
从手推车里拿物品时，如果大于人物负重，物品直接消失

### ISSUE THREAD

**Issue by michaelwoooo** [PandasWS/Pandas#122]
情景重现：
`1、刷几千个道具，刷到人物负重即满为止
2、把道具丢手推车里，人物继续刷负重
3、从手推车里把道具拿出来，如果该道具超过人物负重，该道具直接消失(如果一次性拿出几百上千个的话，一样按拿出数量消失)`

正常应该像仓库拿出来那样，提示负重已满，道具无变化

**Comment by CairoLee** [comment]
刚刚测试了一下，无法重现此问题（能够正常给与提示，道具并不消失），已经录制一个视频发给你确认一下操作步骤是否正确

**Comment by CairoLee** [comment]
目前看来 rAthena 可能已经修复了此问题，先关闭~ 有更进一步的情况可以再打开
