### ISSUE TITLE
reloadnpcfile指令脚本路径后面带空格会导致复制NPC

### ISSUE THREAD

**Issue by zh82558223** [PandasWS/Pandas#132]
* **代码版本**: 问题发现在racn180，所以在这里也提一下，避免panda也出现类似问题。

* **客户端版本**: 20170614

* **工作模式**: 全部

* **问题描述**: 

  * 当前结果:

    > 在游戏内容中反映的情况是 两个NPC叠在一起，如果在输入第二条指令的时候更改NPC坐标，可以看到这一个NPC脚本生成了2个NPC。就是说.txt和.txt空格 是两个NPC了。

  * 预期结果:

    > 预期结果原本以为会读取第一条指令的NPC

  * 重现步骤:

    > 使用reloadnpcfile指令使用的时候，如果在结尾的txt后面加一个空格，会导致这个npc被复制，相当于读取了一个txtnpc和一个txt空格npc.

    > 例如输入以下两条指令：
    > @reloadnpcfile npc/re/ceshi/ceshi.txt
    > @reloadnpcfile npc/re/ceshi/ceshi.txt空格

    > 两个npc内容一致，mapserver还会提示重复的npc。

  * 官方信息: 无

* **可能会影响结果的一些修改**: 

出现该问题的原因：因为测试脚本的时候经常需要重新读取这个脚本...因为服务器设定同一句话发送次数不能超过10次.所以使用在命令后面加空格的方式连续发送.结果导致出现这个问题.

**Comment by CairoLee** [comment]
此问题已经被解决，如果还有与其相关的其他情况，可以重新打开此问题
