### ISSUE TITLE
變量商店消費後, 官方商城點數不會被刷新.

### ISSUE THREAD

**Issue by niu0710** [PandasWS/Pandas#133]
在變量商店設置點數需求為 #CASHPOINTS 進行消費後, 
進入遊戲畫面右上角的商城,
將不會扣除變量商店所花費的點數
可以進行花費

// 測試用NPC
-	pointshop	pointshop_Cashshops2	123,#CASHPOINTS|現金點數,501:5000

iz_int02,20,29,5	script	現金點數交易	11007,{
	callshop "pointshop_Cashshops2",1;
	end;
}

**Comment by CairoLee** [comment]
确认存在此问题

**Comment by CairoLee** [comment]
此问题已经被解决，如果还有与其相关的其他情况，可以重新打开此问题
