### ISSUE TITLE
测试对 mac 地址的记录和利用价值分析

### ISSUE THREAD

**Issue by CairoLee** [PandasWS/Pandas#151]
**您请求实现的功能是否和某个问题相关？描述一下**

在 brAthena 中有一段代码用来获取客户端的 mac 地址，不知道这个mac是游戏客户端的，还是客户端网关的，需要分析一下。顺便看下利用价值，以及什么版本的客户端支持。

**描述一下您喜欢的解决方案**

如果是客户端的mac地址，那么相对来说就有一点利用价值。可以进行多开检测判定。
但是用来做封设备的话，其实意义不会太大。
毕竟mac地址是可以修改的，达不到封禁效果，而多开时候修改mac会掉线……

**其他附加信息**

https://github.com/brAthena/brAthena20180924/commit/51dd5f2cc2fa9967cc65e681d71038ef34e6cd6c

**Comment by jian916** [comment]
要取得 MAC 必須要啟用客戶端的 SSO 功能，測試在 2013 以前都有支持
取得的 MAC 是遊戲客戶端的網卡 MAC
因為支持性不佳，部分系統無法取得 MAC，已被 gravity 捨棄的功能

**Comment by CairoLee** [comment]
2018和2019客户端已经不再具备SSO登陆能力了吗？

**Comment by CairoLee** [comment]
经过测试，在 20180620 的客户端中，SSO 登录能力继续有效~ 因此还是先实现了相关的功能，等待更大范围的验证
