### ISSUE TITLE
希望道具可以用多个 pet 指令，支持捕捉多种魔物

### ISSUE THREAD

**Issue by CairoLee** [PandasWS/Pandas#153]
**您请求实现的功能是否和某个问题相关？描述一下**

希望一个道具可以用多个 pet 指令来指定支持捕捉多种宠物

**描述一下您喜欢的解决方案**

根据官方设定，一个魔物捕捉道具应该只能抓一个宠物；希望能让它支持多个，实现方式比如原来写一个 `pet xxxx;` 现在可以支持写多个就行 `pet xxxx; pet yyyy;` 这样

**其他附加信息**

可能需要考虑一下，Pandas 自己添加的用于识别捕捉道具的相关自定义函数。

以前若值支持一个 pet xxxx; 的话，肯定可以准确读取到 xxxx 这个魔物id，但是若支持多个的话，代码中这个可能也需要进行一些调整

**Comment by jian916** [comment]
這個理論上可行
擴展 pet_db.yml 支持 TameItem 陣列設置
一個魔物可用多種捕捉道具抓取

擴展 pet <pet id>,{<pet id n>}; 指令
一個捕捉道具可抓多種魔物

**Comment by CairoLee** [comment]
对，技术上完全可行。等我把dmp文件分析机制做完，就开始扫 issues

**Comment by CairoLee** [comment]
此问题已解决，如果还有与其相关的其他情况，可以重新打开此问题
