### ISSUE TITLE
当玩家攻击且造成伤害时触发事件

### ISSUE THREAD

**Issue by michaelwoooo** [PandasWS/Pandas#184]
## 你想实现的新功能，是为了解决什么问题？
记忆坑的做法

> *OnPCAttackFilter:

事件描述
	当玩家攻击且造成伤害时触发
	注意: 本事件由BetterRA.conf中 attack_filter_target 配置 与 脚本指令 unitatkeventmark 共同控制
	
参数说明(注意, 返回参数不带任何符号)
	dmg_type 攻击类型(使用位于运算, 计算是不是想要的攻击类型)
	dmg_damage 本次攻击伤害, 最大不超过 2147483647
	dmg_skillid 本次攻击所使用的技能ID, 如果为普通攻击则为0
	dmg_skilllv 本次攻击所使用的技能等级, 如果为普通攻击则为0
	dmg_targettype 本次攻击的目标类型(实体类型)(使用位于运算, 计算是不是想要的类型)
	dmg_targetgid 本次攻击目标的GID
	dmg_mobid 本次攻击目标的魔物ID, 如果不为魔物则为0
	dmg_mark 返回由脚本指令 unitatkeventmark 设置的标记

中断说明: 
	中断后可通过修改 dmg_damage 参数来修改本次伤害的实际值(可设置为0)

攻击类型参数说明:
	按攻击范围:
		BF_SHORT:  近距离攻击
		BF_LONG:   远距离攻击
		默认:   BF_SHORT+BF_LONG
	按攻击类型:
		BF_WEAPON: 武器攻击
		BF_MAGIC:  魔法攻击
		BF_MISC:   混合攻击
		默认:   BF_WEAPON
	按技能类型:
		BF_NORMAL: 普通攻击
		BF_SKILL:  技能攻击
		默认:   如果攻击类型是 BF_WEAPON (only) BF_NORMAL, 否则 BF_SKILL+BF_NORMAL.
	
实体类型参数说明:	
	BL_PC   - 玩家
	BL_PET  - 宠物
	BL_HOM  - 生命体
	BL_MER  - 佣兵
	BL_ELEM - 元素
	

**### 猥琐熊猫咋实现，你随意~**

**Comment by CairoLee** [comment]
风哥你已经在熊猫模拟器中实现了这个事件，所以我就关闭此问题了
