### ISSUE TITLE
rathenacn扩展的mapflags、atcommands

### ISSUE THREAD

**Issue by idamonli** [PandasWS/Pandas#187]
[rAthenaCN_mapflags.txt](https://github.com/PandasWS/Pandas/files/3723035/rAthenaCN_mapflags.txt)
[rAthenaCN_atcommands.txt](https://github.com/PandasWS/Pandas/files/3723036/rAthenaCN_atcommands.txt)

**Comment by CairoLee** [comment]
具体用到了哪些？我不太想闭着眼睛全部加

**Comment by CairoLee** [comment]
地图标记部分，目前除了 `nopet` 还没实现，其他的都已经在 Pandas 中实现了

**Comment by CairoLee** [comment]
rAthenaCN 中的管理员指令，以下几个暂时不计划在熊猫模拟器中实现：

- eventrpt
- policy
- reloadloginconf
- reloadmannerdb
- reloadpolicies

此问题阶段性完成，暂时先关闭了。建议一个 issues 尽量提交一个问题，比较有针对性
