### ISSUE TITLE
setunitdata指令功能异常

### ISSUE THREAD

**Issue by zh82558223** [PandasWS/Pandas#248]
## 缺陷描述

该指令在使用时对怪物的atk1,atk2未达到预期的效果.
MATK1,MAKT2可能存在同样的问题。

## 重现此问题的步骤

请描述您从克隆此工程之后, 是如何一步一步操作, 最终使问题出现的：

使用setunitdata指令修改怪物的atk1、atk2(matk1\matk2)

## 预期的正确行为

使用setunitdata指令理论认为应该会修改怪物攻击力为指定数值。
实际结果因为怪物属性等原因，怪物的攻击力应该是各种属性的计算结果，可能保存在内存中。
（以上猜测来源raorg）
所以导致修改后的atk1、atk2无法达到预期的数值，还有可能会因为怪物自身属性的变化而变小。
随着属性增加可以理解 ，但是实际atk随着属性增加而变低，实在无法理解。
所以认为该指令存在一定问题，至少在修改atk方面 存在异常，其他属性修改暂时没有遇到问题。

## 截图

setunitdata 33/34/35/36 四项参数，无法达到预期数值效果，还可能降低。

https://rathena.org/board/topic/121072-setunitdata-doesnt-change-mobs-atkmatk/#comment-366735
https://rathena.org/board/topic/121834-wrong-calculating-atk-with-setunitdata/#comment-369940

附RA该问题的讨论帖子。

## 程序编译模式 (请完善以下信息):

 - 操作系统: win10
 - 编译工具: VS2019
 - 代码版本: 201908月pandas
 - 封包版本:20180620
 - 工作模式:复兴后

**Comment by zh82558223** [comment]
[http://www.mrohome.net/s/p1.png](url)
[http://www.mrohome.net/s/p2.png](url)
	setunitdata .@mon,UMOB_ATKMIN,1000;
	setunitdata .@mon,UMOB_ATKMAX,2000;
	setunitdata .@mon,UMOB_MATKMIN,1000;
	setunitdata .@mon,UMOB_MATKMAX,2000;
	setunitdata .@mon,UMOB_ADELAY,50;
	setunitdata .@mon,UMOB_STR,100;
	setunitdata .@mon,UMOB_INT,100;
	setunitdata .@mon,UMOB_DEX,100;
	setunitdata .@mon,UMOB_LUK,100;

使用上述指令修改后的前后数值
更正：单独修改33-36参数无变化.....配合素质点数修改出现问题.

**Comment by CairoLee** [comment]
收到，我测试一下

**Comment by CairoLee** [comment]
这个问题在你提供的两个链接中，Seravy 表达的比较清楚。他的意思是：这个四个属性 UMOB_ATKMIN、UMOB_ATKMAX 和  UMOB_MATKMIN、UMOB_MATKMAX 是程序根据魔物的状态值计算出来的伤害波动区间。

在 getunitdata 中可以读取这个伤害区间，但是却不合适使用 setunitdata 来设置他们。因为他们的来源并不是和其他属性一样是从 db 里面读取的、固定的。而是会随着魔物的状态变化（甚至是被玩家套了一个降低攻击力的 DEBUFF）而导致 ATKMIN、ATKMAX 等四个数值被重新计算（所以设置他无意义，因为总会被程序重新计算，这个值维持不了）

因此他给了一个中间解决方案，比如：魔物的 ATKMIN、ATKMAX 是根据他的 STR 等六维属性计算出来的，因此提高 STR 属性来提高魔物的 ATKMIN、ATKMAX 是更加正确的做法。

他提到的这个做法，你这边是否曾经做过验证呢？

**Comment by ShiraGawaAnri** [comment]
STR、INT不单单影响ATKMIN和ATKMAX、MATKMIN和MATKMAX
无论是修改基本素质还是setunitdata，两者都不是最接近理想的实现方案

**Comment by ShiraGawaAnri** [comment]
> STR、INT不单单影响ATKMIN和ATKMAX、MATKMIN和MATKMAX 无论是修改基本素质还是setunitdata，两者都不是最接近理想的实现方案

由于魔物极少修改自身的基础属性，可否考虑怪物刷新后，锁定重新计算这4个属性呢，即debuff套用瞬间或消失瞬间，
以刷新后瞬间的数值UMOB_XXX为基准重新计算
而setunidata则可以改动这个UMOB_XXX的基准

**Comment by CairoLee** [comment]
此问题已解决，如果还有与其相关的其他情况，可以重新打开此问题
