### ISSUE TITLE
無法創建繁體中文名稱人物

### ISSUE THREAD

**Issue by littleeddypan** [PandasWS/Pandas#293]
## 缺陷描述

在創造繁體中文名稱角色後登入，名稱會顯示????
之後將資料庫設定成BIG5後
資料庫確實可以輸入繁體中文了
inter-athena.conf  也設定default_codepage:  big5
但在創造繁體中文名稱角色進入遊戲後就會跳出錯誤

## 重现此问题的步骤
1.main資料庫設定成BIG5
2.inter-athena.conf  也設定default_codepage:  big5
3.執行 ./athena-start start
4.創造繁體中文名稱腳色
5.進入遊戲
6.模擬器就跳錯

## 预期的正确行为
順利進入遊戲  並正常顯示繁體中文

## 截图
![1593309373618](https://user-images.githubusercontent.com/7518810/85936670-6e19af80-b92f-11ea-9029-79fdf8208d47.jpg)

## 程序编译模式 (请完善以下信息):

 - 操作系统: centos 7
 - 编译工具: CMake
 - 代码版本: Hash
 - 封包版本:20180620
 - 工作模式: 复兴后

**Comment by CairoLee** [comment]
根据上图的提示，看起来程序陷入了一个死循环调用。当他尝试将gbk编码转换成utf8编码的时候，失败了。请在终端输入`locale` 回车并将显示的结果发出来吗？

**Comment by CairoLee** [comment]
此问题确认已经修复，请等待 1.0.7 版本，或使用 develop 分支先行测试。

---

- 数据库全部建立为 big5
- default_codepage 保持为 auto 或者 big5 都行
- 终端控制台中输入 locale 确认一下当前使用的编码
- 必须是 zh_TW.utf8 才能避免终端里显示角色名乱码
  - 但其实终端里显示乱码，也不影响游戏内的正常显示
- 如果不是 zh_TW.utf8 那么请输入 locale -a 确认是否返回的列表中存在 zh_TW.utf8 选项
  - 如果存在，那么可以继续
  - 如果不存在，说明系统没安装中文语言包，先去搜索一下寻找安装方法
- 当确认语言包安装后，使用 export LANG="zh_TW.utf8" 然后再试试
  - 预期是：此时终端显示的信息都是繁体中文，繁体中文的角色名也能正常显示
  - 注意：export 只是临时修改，重启终端后就会被重置，若想开机就是 zh_TW.utf8 得将指令写入一个打开 shell 就会被自动执行的位置，具体可以上网找一下，通常只要讲到 export LANG=xxxx 的地方都会提到

---

此问题暂时关闭，如果还是继续故障，请打开此问题。
