### ISSUE TITLE
 systemLanguage 和 consoleEncoding 一致的时候 不应该再启动编码转换

### ISSUE THREAD

**Issue by flufy3d** [PandasWS/Pandas#295]
第一次调用 ShowInfo 会把 后面的这个 latin1 值 吃掉
导致 charset 初始化失败
后面两个数据库的设置就没有问题

[Info]: Pandas Version: v1.0.7-dev
[Info]: Console translation system was deactivated.
[Info]: Diagnostic information: Langinfo: UTF-8 | Locale: C.UTF-8
[Warning]: You are running rAthena with root privileges, it is not necessary.
[Info]: Server uses 'select' as event dispatcher
[Info]: Server supports up to '1024' concurrent connections.
[Info]: Server crashdump file will be saved to: 'dumps/'
[Info]: Finished reading conf/import/inter_conf.txt.
[Info]: Finished reading conf/inter_athena.conf.
[Info]: Finished reading conf/import/login_conf.txt.
[Info]: Finished reading conf/login_athena.conf.
[Info]: Done reading '0' messages in 'conf/msg_conf/import/login_msg_conf.txt'.
[Info]: Done reading '23' messages in 'conf/msg_conf/login_msg.conf'.
[Info]: Detected the Log database character set is latin1.
[SQL]: DB error - Can't initialize character set (path: /usr/share/mysql/charsets/)
[Debug]: at /root/Pandas/src/login/loginlog.cpp:226 - SHOW VARIABLES LIKE 'character_set_database';
[Info]: Ipban connection made.
[Info]: Detected the Ipban database character set is latin1.
[Info]: Server will connect to 'Ipban' database using 'latin1'.
[Info]: Detected the Login-Server database character set is latin1.
[Info]: Server will connect to 'Login-Server' database using 'latin1'.
[Status]: The login-server is ready (Server is listening on the port 6900).

**Comment by CairoLee** [comment]
请合并 #298 或者切换到 bugfix/issue294 分支进行测试，若问题已经解决，请告知。若未解决，请再帮忙描述一下详细的情况

**Comment by CairoLee** [comment]
此问题已解决，如果还有与其相关的其他情况，可以重新打开此问题

**Comment by flufy3d** [comment]
测试了下 问题解决了
