### ISSUE TITLE
[錯誤] comf/groups.conf:1 - syntax error     (已找出問題)

### ISSUE THREAD

**Issue by black661** [PandasWS/Pandas#335]
只要修改 groups.conf     map伺服器就會跳   [錯誤] comf/groups.conf:1 - syntax error

我只是將groups.conf  底部的  all_skill: false  改成 all_skill: true   

改其他的也會跳這種錯誤comf/groups.conf:1 - syntax error       即使改回去原本的 也是會跳錯誤

角色一進入遊戲就卡住了  不能動

部分人有幫我測試   都表示功能正常

可是我重載 再使用一次 也是一樣 

這是我在架設的過程中 哪邊沒修改到嗎?

問題原因 使用win7內建記事本做修改 會導致編碼更動

**Comment by CairoLee** [comment]
感谢你处理完成后还给予了反馈！

在 rAthena 项目中（熊猫模拟器基于 rAthena 构建）后缀为 conf 的文件使用 libconfig 进行加载。当前只能使用 ANSI 编码（GBK或 BIG5）而不能使用 Unicode 编码（UTF8、UTF8-BOM）

在 yml 类型的文件中，熊猫模拟器自动进行了编码转换（因此可以用 UTF8-BOM），但 conf 暂时不行。请将编码调整正确即可。通常这类型的报错都是在第一行

**Comment by CairoLee** [comment]
此问题已解决，如果还有与其相关的其他情况，可以重新打开此问题
