### ISSUE TITLE
無法正常開啟客戶端

### ISSUE THREAD

**Issue by 2019wei** [PandasWS/Pandas#357]
有照著流程,成功產生出2018-06-20eRagexe_patched 登入器,不過點下去 就出現錯誤,不知道是不是語系問題造成的
![image](https://user-images.githubusercontent.com/46859361/110758287-54cf4e00-8287-11eb-91d0-e344086b4789.png)
![image](https://user-images.githubusercontent.com/46859361/110758315-5c8ef280-8287-11eb-88a9-3c56ff9ea249.png)
![image](https://user-images.githubusercontent.com/46859361/110758409-74667680-8287-11eb-8ce7-a99e10416eba.png)

**Comment by a30678** [comment]
是語系編碼問題

**Comment by CairoLee** [comment]
LeeClient 对繁体中文系统暂时不是非常的友好，得等我找时间处理了

**Comment by CairoLee** [comment]
关于这个问题，我说一下原因：

在 grf 文件中，所有的文件名都是以 ansi 规范的韩文编码（Codepage：949）保存的。当这些韩文编码被我们通过一些 grfeditor 的工具解压出来之后，根据操作系统语言的不同会变成不同的字符（严谨的说，并不是根据操作系统语言变化的，因为 grfeditor 可以自己选择编码，只不过在简体中文系统上如果你不选择使用正确的编码，那么解压出来的档案无法被 Ragexe.exe 读取，因此为了解压出来的档案可用，我们都会在 grfeditor 中选择与自己系统语言匹配的编码），比如：

- 韩文编码下（Codepage = 949）：유저인터페이스 意思是：用户界面
- 简中编码下（Codepage = 936）：蜡历牢磐其捞胶
- 繁中编码下（Codepage = 950）：嶸盪檣攪檜蝶

当 data 中的文件被解压打散之后，不同语言下的 ragexe 会去用不同的字符尝试去读取文件路径。接下来的问题来了～ 我在构建 Leeclient 的情况下，data 目录中的文件是在简体中文环境下解压的。因此它的文件名会变成类似：蜡历牢磐其捞胶；随后，使用 git 将文件提交到 github 的时候，git 的文件路径使用的是 unicode 编码，也就是说：它会原封不动的保留：蜡历牢磐其捞胶 这样的字符，然后在繁体中文系统上你拉取 leeclient 后，你会发现 data/texture 目录中也是：蜡历牢磐其捞胶（但你必须变成：嶸盪檣攪檜蝶）客户端才能正常工作，否则就会瞬间退出。

我一直没能找到一个简单的办法，比如让 git 回到以 ansi 规范的方式来保存文件路径。让他在简体中文系统上解压的时候用：蜡历牢磐其捞胶 在繁体中文系统上解压用：嶸盪檣攪檜蝶。所以一直搁置到现在～

昨天晚上有一个新的想法，我随后会找时间验证。此问题属于 leeclient 项目的问题，因此我将关闭它。
