### ISSUE TITLE
無法取得正確的BOSS屬性

### ISSUE THREAD

**Issue by jian916** [PandasWS/Pandas#366]
https://github.com/PandasWS/Pandas/blob/413beb9e79e1841ee59696b0108a388bb60e2549/src/map/map.cpp#L2105

在執行 mob_spawn 後會將 md->state 重置
造成 md->state.boss 取到不正確的狀態
改成 if (md->spawn->state.boss)

**Comment by CairoLee** [comment]
此判断确实没必要，已经将这个判断条件移除。
当一个魔物明确在 bossid_db 中，那么直接对他的 GameID 进行更新即可。
