### ISSUE TITLE
BOSS雷達效果無法持續

### ISSUE THREAD

**Issue by jian916** [PandasWS/Pandas#367]
## 缺陷描述

https://github.com/PandasWS/Pandas/blob/413beb9e79e1841ee59696b0108a388bb60e2549/src/map/status.cpp#L10813

BOSS雷達用SC狀態紀錄當前地圖BOSS的GID
魔物重生後map_mobiddb刷新UID這會讓當次的雷達效果消失
https://github.com/PandasWS/Pandas/blob/413beb9e79e1841ee59696b0108a388bb60e2549/src/map/map.cpp#L2081

## 重现步骤

使用BOSS雷達(12214)顯示當前地圖的BOSS
擊殺BOSS後當次的雷達效果直接消失

## 预期的正确行为

BOSS雷達應該要持續顯示BOSS位置

## 其他附加信息

mob_delayspawn魔物重生時map_mobiddb刷新UID是因為方便腳本讀取數據嗎
是否有必要更換單位編號UID
這樣好像不是理想的方法
可能有其它跟BOSS雷達一樣的狀況
例如跟 bl 有關聯結構的問題 master_id、target_id、src_id、guardian、SC狀態保存UID 等等很多應用
每個結構都去刷新好像不切實際

**Comment by CairoLee** [comment]
好久不见，你提到的问题已经被修复

----

引入了战斗记录机制后，为了能够让脚本作者更精准的跟踪每一个魔物的战斗记录，必要的时候可以随意调取，而不用考虑当前的魔物是否已经死过。因此调整了一下，让魔物死亡后重新召唤时更新他们的 GameID。

之前一直以为每个魔物的 GameID 都是独一无二的，直到上次看代码才发现：设置了刷怪点的魔物他们的 GameID 是被固定的，每次死亡后重新刷新新出现的魔物 GameID 与之前一致；只有临时召唤出来的魔物才会获得新的 GameID。

----

我在 status.cpp 文件中通过搜索 bl.id 和 bl->id，仅发现 SC_BOSSMAPINFO 会引入 bl.id 并将其记录下来。而其他与魔物 GameID 相关的数据库，都已经根据 map_addiddb 进行了处理。

https://github.com/PandasWS/Pandas/blob/413beb9e79e1841ee59696b0108a388bb60e2549/src/map/map.cpp#L2046

**Comment by jian916** [comment]
我指的不是只有 bossid_db 問題
mobid_db、id_db 也有更換 GID
mobid_db > map_id2md、map_foreachmob
id_db > map_id2bl、mapit_alloc
這邊的關聯就像樹狀結構一樣發散出去
具體會影響什麼還要再確認，或等問題回報
刷怪點的魔物我們稱自然重生
自然重生魔物也會存在 mobid_db 及 id_db
繞一圈去刷新所有 GID，才會說這樣比較不切實際
當然 UID 就應該是唯一值，不可否認

如果 map_mobiddb 刷新後的 GID 也能返回就更完美了
在 NPCE_KILLNPC 判斷是否是自然重生，取得新 GID 存入 md 並返回變數
有時候控制所有 BOSS 的屬性、或是判斷生死狀態，會需要新 GID

另外戰鬥紀錄應該比較少會用到這麼複雜
大部分還是腳本召喚、腳本控制

**Comment by CairoLee** [comment]
感谢回复，之前一直在出差~ 关于你提到的问题，咱可以继续讨论一下。

> 我指的不是只有 bossid_db 問題
> mobid_db、id_db 也有更換 GID
> mobid_db > map_id2md、map_foreachmob
> id_db > map_id2bl、mapit_alloc
> 這邊的關聯就像樹狀結構一樣發散出去
> 具體會影響什麼還要再確認，或等問題回報
> 刷怪點的魔物我們稱自然重生
> 自然重生魔物也會存在 mobid_db 及 id_db
> 繞一圈去刷新所有 GID，才會說這樣比較不切實際
> 當然 UID 就應該是唯一值，不可否認

我理解你的担心，不过根据我目前看到的表现，应该结果是可控的，理由如下：

- 只有魔物自然重生单位，会被熊猫更新 GID，其他类型的单位不会也不需要
- 理论上一个魔物单位死亡，那么与它相关的所有 GID 关联，应该被清理（SC、Timer等）
  - 我重新确认了一下，确实如此
  - 当时如果我仔细确认了 bl->id 的利用的话，应该可以发现 SC_BOSSMAPINFO，但也只有它
- 最终 `map_mobiddb` 刷新处理的那些东西，都参考自 `map_addiddb` 应该不会有啥遗漏，如果真有等汇报吧

> 如果 map_mobiddb 刷新後的 GID 也能返回就更完美了

- 当前 `map_mobiddb` 分配的新 GID 是外部调用传入的，因此他自己返回的意义不大
  - 调用 `map_mobiddb` 需要传入 `new_blockid` 来指定新的 GID，因此调用者本身已经明确了新的 GID
  - 不过倒是可以调整成 `new_blockid` 不是必须，如果传入 -1 则自动生成，并将新的 GID 返回

> 在 NPCE_KILLNPC 判斷是否是自然重生，取得新 GID 存入 md 並返回變數
> 有時候控制所有 BOSS 的屬性、或是判斷生死狀態，會需要新 GID

- 目前刷新 GID 的流程，是在自然重生魔物即将“重生”的时候，才会执行刷新操作
- 想要满足你提到的需求，需要改成自然重生魔物一旦死亡立刻刷新 GID，且将新的 GID 通过死亡事件传递给脚本
- 判断生死状态的时候，除了判断 unitexists 还需要判断 HP 是否为 0 才能知道单位死活
  - 哪怕在战斗记录没被引入的时候，也需要如此判断
- 或许直接提供一个：GID 刷新事件（不会被事件队列阻塞的实时事件），并将魔物原先的 GID、新的 GID 一起提供，是否也能解决脚本的刷新需求？

**Comment by CairoLee** [comment]
再次感谢 Jian916 的反馈，鉴于BOSS雷达相关问题已经在 #369 中修正，此问题暂时关闭
