### ISSUE TITLE
您好 關於不定時 map-server 崩潰問題

### ISSUE THREAD

**Issue by qsc7831449** [PandasWS/Pandas#378]
您好，最近遇到這項問題，想請教您，由於本身專業度不夠，也有自己簡單評估，
但還是認為，需要給予你們專業人士去做判斷與評估，以下是敘述 :
目前使用版本 : Pandas_v1.1.3_20210705_112212_RE_BIG5
相關使用工具 : Navicat Premium 15 (服務器版本10.5.11-MariaDB) + HeidiSQL
模擬器內有加載許多NPC腳本，但並未顯示有錯誤訊息
當玩家人數眾多時(經自己觀察是開啟副本、活動NPC)，就會導致 map-server崩潰
然而崩潰後，大約30分~1小時之後，同樣類似狀況出現
是否與我本身，設定有所錯誤導致崩潰
希望能與你一番討論後，找出原因，謝謝您

錯誤圖檔01
https://i.imgur.com/KYu78ks.png

錯誤圖檔02
https://i.imgur.com/eMSoDhM.png

錯誤記錄檔
https://drive.google.com/file/d/1Y30p8ln1T33nq4407AFXOpP1uOW2QbVF/view?usp=sharing

下列為之前使用XAMPP 紀錄文字 (是否為log與main數據庫共用關聯...)
2021-07-05  8:46:08 10 [ERROR] mysqld.exe: Table '.\racn2\loginlog' is marked as crashed and should be repaired
2021-07-05  8:46:08 10 [Warning] Checking table:   '.\racn2\loginlog'
2021-07-05  8:46:08 11 [ERROR] mysqld.exe: Table '.\racn2\ipbanlist' is marked as crashed and should be repaired
2021-07-05  8:46:08 11 [Warning] Checking table:   '.\racn2\ipbanlist'
2021-07-05  8:46:08 12 [ERROR] mysqld.exe: Table '.\racn2\char' is marked as crashed and should be repaired
2021-07-05  8:46:08 12 [Warning] Checking table:   '.\racn2\char'
2021-07-05  8:46:08 12 [ERROR] mysqld.exe: Table '.\racn2\guild' is marked as crashed and should be repaired
2021-07-05  8:46:08 12 [Warning] Checking table:   '.\racn2\guild'
2021-07-05  8:46:08 12 [ERROR] mysqld.exe: Table '.\racn2\hotkey' is marked as crashed and should be repaired
2021-07-05  8:46:08 12 [Warning] Checking table:   '.\racn2\hotkey'
2021-07-05  8:46:08 12 [ERROR] mysqld.exe: Table '.\racn2\sc_data' is marked as crashed and should be repaired
2021-07-05  8:46:08 12 [Warning] Checking table:   '.\racn2\sc_data'
2021-07-05  8:46:08 12 [ERROR] mysqld.exe: Table '.\racn2\inventory' is marked as crashed and should be repaired
2021-07-05  8:46:08 12 [Warning] Checking table:   '.\racn2\inventory'
2021-07-05  8:46:08 12 [ERROR] mysqld.exe: Table '.\racn2\charlog' is marked as crashed and should be repaired
2021-07-05  8:46:08 12 [Warning] Checking table:   '.\racn2\charlog'
2021-07-05  8:46:08 12 [ERROR] mysqld.exe: Table '.\racn2\char_reg_str' is marked as crashed and should be repaired
2021-07-05  8:46:08 12 [Warning] Checking table:   '.\racn2\char_reg_str'

**Comment by CairoLee** [comment]
![image](https://user-images.githubusercontent.com/4458917/125165531-eadd9b80-e1c9-11eb-9085-6906b7c61633.png)

分析 dmp 文件至少需要崩溃的exe文件，以及在建置同时出现的 pdb 文件，否则分析无法进行。

您可以尝试打开 dmp 文件后点击右上角绿色箭头，如上图所示。然后看看 Visual Studio 是否能帮您定位到崩溃的代码行，如果能，截图我看下。

亦或者，您可以将刚刚提到的：dmp（已发送）、exe（未发送）、exe建置时对应的 pdb 文件（未发送）附加到回复中上传，谢谢

**Comment by CairoLee** [comment]
此外，后面的 XAMPP 日志，看起来应该是他探测到 mysql server 崩溃。与熊猫本身的崩溃可能不相关（但也有可能熊猫的崩溃是 mysql 崩溃引起的，或者反过来）。等候您提供相关文件进行分析

**Comment by qsc7831449** [comment]
好的，謝謝您願意抽出時間來替我解答，請稍等片刻，我將給予資訊。

**Comment by qsc7831449** [comment]
您好，因為我不太會使用Visual Studio 
所以不太知道 您需要的 是不是這段訊息
https://imgur.com/tox0Vmm

**Comment by CairoLee** [comment]
是的，但目前显示的是汇编代码，我无法轻易定位。有可能是 dmp/exe/pdb 三者不匹配导致的，也有可能是崩溃的位置没有代码导致的。

请尝试点击右下角的“调用堆叠”，看看是否能有更多信息：

![image](https://user-images.githubusercontent.com/4458917/125168239-0d29e600-e1d7-11eb-916c-862d4b785e52.jpeg)

**Comment by qsc7831449** [comment]
十分感謝您的幫忙，圖下已呼叫堆疊
![Image of Yaktocat](https://imgur.com/FWyN1qp.png)

再麻煩有勞您了，十分感謝。

**Comment by CairoLee** [comment]
根据您提供的截图，pdb和崩溃的程序不匹配。请按如下操作执行：

1、重新建置一份全新的Release模式的程式
2、将生成的 exe 和 pdb 文件，还有src目录，复制出来备份到另外一个文件夹
3、拿着新建置出来的exe，替换到您的开服环境，用它开服
4、等待再次出现崩溃，将 dmp 文件保存起来

---

发生崩溃之后：

1、将src目录内容和备份的exe、pdb复制回到他们原来在备份之前所处的路径
2、双击 dmp 再点绿色箭头，应该就可以看到崩溃的所在代码行

**Comment by qsc7831449** [comment]
好的謝謝您，我盡量嘗試看看，很感謝你的回答

**Comment by qsc7831449** [comment]
明白您的詳細說明，不好意思....一時間腦子不好使....
目前已經編譯出一份exe，完全按照您得操作進行
之後產出的 dmp 及 崩溃的所在代码行
再向上回報給您知道一下，很感謝您細心回答問題。

**Comment by CairoLee** [comment]
好的，我在此等待您新的讯息

**Comment by CairoLee** [comment]
请问是否有新的进展？或者崩溃情况？

**Comment by qsc7831449** [comment]
您好 關於 地圖崩潰的問題點，我套用重新編譯後的.exe之後，就沒有出現過這個問題，觀察了好幾個禮拜後，發現沒有這項問題了，後續我再觀察看看，謝謝您^^~

**Comment by qsc7831449** [comment]
![Image of Yaktocat]([img]https://i.imgur.com/w6mG0mB.png[/img])
目前得知!! 好像是這個問題

下列為 : exe、dumps、圖示
https://drive.google.com/file/d/1Biqq5mvi0vkBGgxi18e-lB7S6JN5hWcN/view?usp=sharing

**Comment by qsc7831449** [comment]
想詢問以上錯誤點，是否來至，郵件附加物品重量問題
// 可以附在邮件上的最大总重量
// NOTE: this limit is hardcoded in the client, you need to diff your client accordingly if you change this value.
// Default: 2000
// 0 = No weight limit
mail_attachment_weight: 2000

下列影片，是郵件的一項BUG(親自測試，可以行得通哈哈)
https://www.youtube.com/watch?v=K8Ijhr44QYU

目前更改
mail_attachment_weight: 2000 → mail_attachment_weight: 0
再觀察看看 之後再向您回報 謝謝您^^~

**Comment by CairoLee** [comment]
收到，将在明天分析

**Comment by qsc7831449** [comment]
這是後續資料(dumps比較多檔案可以分析)
https://drive.google.com/file/d/1U-Rzk6h_E7vigdXPIQWX5QPmJOQmcxlP/view?usp=sharing
再麻煩您了感謝，若還需要其它資料，這一邊都方便提共您^^~

**Comment by CairoLee** [comment]
您好，我还需要一个 map-server.pdb （必须是您当时编译 map-server.exe 时同时生成出来的那个），不知道您那边是否有保存，如果有请发给我

**Comment by qsc7831449** [comment]
您好這是跟後續資料一起編譯出來的 map-server.pdb及其它個2
再麻煩您了謝謝，不好意思沒有補上來給您
https://drive.google.com/file/d/1xd-RFy3ScSi4MZZtwV82UOxv9CVvNZd8/view?usp=sharing

**Comment by CairoLee** [comment]
> 想詢問以上錯誤點，是否來至，郵件附加物品重量問題
> // 可以附在邮件上的最大总重量
> // NOTE: this limit is hardcoded in the client, you need to diff your client accordingly if you change this value.
> // Default: 2000
> // 0 = No weight limit
> mail_attachment_weight: 2000
> 
> 下列影片，是郵件的一項BUG(親自測試，可以行得通哈哈)
> https://www.youtube.com/watch?v=K8Ijhr44QYU
> 
> 目前更改
> mail_attachment_weight: 2000 → mail_attachment_weight: 0
> 再觀察看看 之後再向您回報 謝謝您^^~

虽然与崩溃无关，但这确实是 rAthena 的一个缺陷，已经在 https://github.com/PandasWS/Pandas/commit/14387012560d5de43d25d9571e0a618c250c8c1d 修复了，您可以试试

**Comment by qsc7831449** [comment]
好的謝謝您，目前我在編譯一下試試看，若有更新的錯誤再與您聯繫，很感謝您的分析

**Comment by CairoLee** [comment]
此外，其他几个崩溃得益于您提供的 pdb 文件，分析的结果基本都是一致的，请应用：https://github.com/PandasWS/Pandas/commit/c564bfcb951d77d87eeb9ea15c8d4f2bd3d6a929 和 https://github.com/PandasWS/Pandas/commit/d8b3e98139f288369ba97ddc0441c6f138461bb3 应该就不会再崩了

另外我想问一下，您知道如何触发这个崩溃吗？我之前分析应该是客户端恶意构造了发封包的顺序导致的，但我并不肯定；如果您有触发这个崩溃的方法，可以告诉我一下

**Comment by qsc7831449** [comment]
目前崩潰點，我也無法得知，但感覺與您述說的惡意行為比較相似，感覺是有部分惡意人士利用這幾點來導致崩潰。

**Comment by CairoLee** [comment]
好，那您先按之前的两个补丁试试。有新的崩溃点再反馈，如果观察一段时间没问题的话，记得回来把 issue 关闭

**Comment by qsc7831449** [comment]
想詢問以上觀點 是否為我的封包碼是直接套用預設2018，而沒有做封包混淆的關係

**Comment by qsc7831449** [comment]
若是可以的話，這邊也方便給予你，客戶端及服務端放便給予您作為，開發及錯誤尋找

**Comment by qsc7831449** [comment]
> 好，那您先按之前的两个补丁试试。有新的崩溃点再反馈，如果观察一段时间没问题的话，记得回来把 issue 关闭

好的謝謝您，我將再測試一周期看看，是否有任何崩潰點出現

**Comment by qsc7831449** [comment]
> 您好，最近遇到這項問題，想請教您，由於本身專業度不夠，也有自己簡單評估，
> 但還是認為，需要給予你們專業人士去做判斷與評估，以下是敘述 :
> 目前使用版本 : Pandas_v1.1.3_20210705_112212_RE_BIG5
> 相關使用工具 : Navicat Premium 15 (服務器版本10.5.11-MariaDB) + HeidiSQL
> 模擬器內有加載許多NPC腳本，但並未顯示有錯誤訊息
> 當玩家人數眾多時(經自己觀察是開啟副本、活動NPC)，就會導致 map-server崩潰
> 然而崩潰後，大約30分~1小時之後，同樣類似狀況出現
> 是否與我本身，設定有所錯誤導致崩潰
> 希望能與你一番討論後，找出原因，謝謝您
> 
> 錯誤圖檔01
> https://i.imgur.com/KYu78ks.png
> 
> 錯誤圖檔02
> https://i.imgur.com/eMSoDhM.png
> 
> 錯誤記錄檔
> https://drive.google.com/file/d/1Y30p8ln1T33nq4407AFXOpP1uOW2QbVF/view?usp=sharing
> 
> 下列為之前使用XAMPP 紀錄文字 (是否為log與main數據庫共用關聯...)
> 2021-07-05 8:46:08 10 [ERROR] mysqld.exe: Table '.\racn2\loginlog' is marked as crashed and should be repaired
> 2021-07-05 8:46:08 10 [Warning] Checking table: '.\racn2\loginlog'
> 2021-07-05 8:46:08 11 [ERROR] mysqld.exe: Table '.\racn2\ipbanlist' is marked as crashed and should be repaired
> 2021-07-05 8:46:08 11 [Warning] Checking table: '.\racn2\ipbanlist'
> 2021-07-05 8:46:08 12 [ERROR] mysqld.exe: Table '.\racn2\char' is marked as crashed and should be repaired
> 2021-07-05 8:46:08 12 [Warning] Checking table: '.\racn2\char'
> 2021-07-05 8:46:08 12 [ERROR] mysqld.exe: Table '.\racn2\guild' is marked as crashed and should be repaired
> 2021-07-05 8:46:08 12 [Warning] Checking table: '.\racn2\guild'
> 2021-07-05 8:46:08 12 [ERROR] mysqld.exe: Table '.\racn2\hotkey' is marked as crashed and should be repaired
> 2021-07-05 8:46:08 12 [Warning] Checking table: '.\racn2\hotkey'
> 2021-07-05 8:46:08 12 [ERROR] mysqld.exe: Table '.\racn2\sc_data' is marked as crashed and should be repaired
> 2021-07-05 8:46:08 12 [Warning] Checking table: '.\racn2\sc_data'
> 2021-07-05 8:46:08 12 [ERROR] mysqld.exe: Table '.\racn2\inventory' is marked as crashed and should be repaired
> 2021-07-05 8:46:08 12 [Warning] Checking table: '.\racn2\inventory'
> 2021-07-05 8:46:08 12 [ERROR] mysqld.exe: Table '.\racn2\charlog' is marked as crashed and should be repaired
> 2021-07-05 8:46:08 12 [Warning] Checking table: '.\racn2\charlog'
> 2021-07-05 8:46:08 12 [ERROR] mysqld.exe: Table '.\racn2\char_reg_str' is marked as crashed and should be repaired
> 2021-07-05 8:46:08 12 [Warning] Checking table: '.\racn2\char_reg_str'

**Comment by CairoLee** [comment]
确认解决了？如果还有崩溃的情况，请新开issue 反馈，感谢！

**Comment by qsc7831449** [comment]
> 确认解决了？如果还有崩溃的情况，请新开issue 反馈，感谢！

您好，目前得知原先的問題已經解決，很感謝您 !!，後續若是有出現不一樣的崩潰點，我會再提出問題點給您，之前的崩潰點問題，我懷疑是其他玩家們利用信件漏洞，做一些奇怪的事情或是複製物品之類的都有可能，但是並未很確定，所以不敢肯定說是那樣，目前也還在調查東。

**Comment by CairoLee** [comment]
> > 确认解决了？如果还有崩溃的情况，请新开issue 反馈，感谢！
> 
> 
> 
> 您好，目前得知原先的問題已經解決，很感謝您 !!，後續若是有出現不一樣的崩潰點，我會再提出問題點給您，之前的崩潰點問題，我懷疑是其他玩家們利用信件漏洞，做一些奇怪的事情或是複製物品之類的都有可能，但是並未很確定，所以不敢肯定說是那樣，目前也還在調查中。

重现的方法已经有所猜测，正在验证中，不过并不打算公开，避免被恶意利用…

**Comment by qsc7831449** [comment]
> > > 确认解决了？如果还有崩溃的情况，请新开issue 反馈，感谢！
> > 
> > 
> > 您好，目前得知原先的問題已經解決，很感謝您 !!，後續若是有出現不一樣的崩潰點，我會再提出問題點給您，之前的崩潰點問題，我懷疑是其他玩家們利用信件漏洞，做一些奇怪的事情或是複製物品之類的都有可能，但是並未很確定，所以不敢肯定說是那樣，目前也還在調查中。
> 
> 重现的方法已经有所猜测，正在验证中，不过并不打算公开，避免被恶意利用…

謝謝您，因為和我猜想的有點一樣的地方是，部分惡意玩家身上出現，不屬於本身應有的物品數量，甚至上千個、上萬個。
所以 才會猜想，相關問題點是利用這點來，進行不正當遊戲行為。
