### ISSUE TITLE
Ubuntu 16.04 如何運行python腳本（imple_translate.py）？

### ISSUE THREAD

**Issue by s11005349** [PandasWS/Pandas#381]
作業系統使用Ubuntu 16.04桌面版
目前已經成功使用 pip install pipenv 安装 pipenv
也已經使用 cd 指令切换到 tools\python 目录
但是使用pipenv install時報錯
錯誤訊息如下：
![image](https://user-images.githubusercontent.com/30567162/125191882-3d28c600-e277-11eb-976e-a6aa612dbd5f.png)

若改為使用pipenv run imple_translate.py
則報錯如下：
Error: the command imple_translate.py could not be found within PATH or Pipfile's [scripts].

## 做过哪些研究或尝试
已經嘗試升級python3.6 並設定pyhton3.6為預設 但並沒有解決問題
已經嘗試使用pip install pyyaml 企圖解決pipenv install時的ERROR: Couldn't install package: pyyaml 但無效 重新pipenv install仍然失敗
已經嘗試在網上搜尋報錯訊息，但似乎鮮少有此討論，或者建議方法嘗試無效

## 其他附加信息
无

**Comment by CairoLee** [comment]
已经收到您的反馈，请给我一些时间进行核实，并寻找解决方案

**Comment by s11005349** [comment]
> 已经收到您的反馈，请给我一些时间进行核实，并寻找解决方案

更新進度
剛才得知Ubuntu 16.04並不支援Python3.6
即便安裝也會造成大量錯誤
而按照本篇報錯，有可能需要Python >= 3.6才可以使用ReadME中的方法運行腳本
懇求開發者提供適合Ubuntu 16.04的解決辦法

**Comment by CairoLee** [comment]
我将于明天早上开始探索解决方案，虚拟机已经在安装了！不好意思前几天公司的事情比较忙

**Comment by CairoLee** [comment]
### 已经探索出可行的解决方案，总结一下：

- 在 Ubuntu 16.04 Desktop 中安装 Python 3.8 版本
- 再去执行 imple_translate.py
- 在测试过程中，发现 pdbparse 无法在 linux 环境下安装，已经提交相关代码进行修正（将整合到 1.1.4 正式版）

### 环境说明

- 使用 VMware 虚拟机构建了纯净的 Ubuntu 16.04 系统

### 操作步骤

1. 首先进入管理员模式，后续指令都需要管理员权限运行：`sudo -i`
2. 安装辅助模块：`sudo apt install software-properties-common`
3. 安装第三方应用源：`sudo add-apt-repository ppa:deadsnakes/ppa` 需要按回车确认
4. 更新源数据：`sudo apt-get update`
5. 安装 Python 3.8 版本：`sudo apt install python3.8 python3.8-gdbm python3.8-distutils`
6. 检查安装结果：`python3.8 --version`
7. 准备安装 pip 程序，先安装个 curl（已有则跳过）：`sudo apt install curl`
8. 下载 get-pip 脚本：`curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py`
9. 用 python 3.8 运行刚刚下载的脚本：`sudo python3.8 get-pip.py`
10. 确认安装结果：`pip3.8 --version`

至此，已经完成了对 python 3.8 的安装

> 请不要试图将 python3.8 软连接到 python3 指令，可能会导致 ubuntu 中的部分功能不正常（在我这边看的话，强行改变 python3 命令的软连接，无法打开设置界面的“语言设置”面板）

#### 随后我们开始克隆熊猫仓库：

1. 先安装个 git 指令（有则跳过）：`sudo apt install git`
2. 克隆熊猫仓库到本地：`git clone https://github.com/PandasWS/Pandas.git`
3. 安装 pipenv 指令：`pip3.8 install pipenv`
4. 前往熊猫辅助脚本目录：`cd ~/Pandas/tools/python`
5. 安装依赖：`pipenv install`
6. 进入虚拟环境：`pipenv shell`
7. 执行你需要的脚本：`python ./imple_translate.py`

![image](https://user-images.githubusercontent.com/4458917/126036750-585aa100-f2af-4b61-a72b-71b114cb6e25.png)

**Comment by s11005349** [comment]
謝謝!
等工作到一段落馬上測試
太感謝您了!
辛苦了

**Comment by CairoLee** [comment]
相关修正代码已经合并到 develop 分支，如果您要进行测试的话，请在克隆完成熊猫的仓库后，切换到 develop 分支

**Comment by CairoLee** [comment]
已经合并到 master 分支，可以直接克隆，不用再切换分支了

**Comment by CairoLee** [comment]
此问题已解决，如果还有与其相关的其他情况，可以重新打开此问题
