### ISSUE TITLE
技能等级上限感觉修改无效

### ISSUE THREAD

**Issue by zh82558223** [PandasWS/Pandas#383]
## 缺陷描述

bonus中的bonus3 bAutoSpell效果，当技能等级超过13级，所有技能会出现未知时间的技能延迟。

## 重现步骤
修改 skill.hpp 第38、39行最大技能上限为100
![修改位置](https://user-images.githubusercontent.com/14066453/125200586-5e50dd00-e29e-11eb-9da5-9908d5e5616f.png)

给装备增加如下bonus效果：
bonus3 bAutoSpell,"MG_COLDBOLT",80,1000;
进入游戏，当普通攻击触发80级冰箭时，全技能变黑（技能延迟状态）。
![问题](https://user-images.githubusercontent.com/14066453/125200609-6dd02600-e29e-11eb-943f-4285c1ac3778.png)

下线小退后恢复正常！
![正常](https://user-images.githubusercontent.com/14066453/125200616-71fc4380-e29e-11eb-83da-b09d00fad82c.png)

## 预期的正确行为

预期正确行为应该是正常触发80级冰箭后，技能延迟按照冰箭术的技能延迟
skilldb.yml中的冰箭术 延迟为如下
AfterCastActDelay: 300
所有技能延迟0.3秒

## 程序编译模式 (请完善以下信息):

 - 操作系统: [Windows 10 x64]
 - 编译工具: [Visual Studio 2019 社区版]
 - 代码版本: [1.1.3]
 - 封包版本: [20200304]
 - 工作模式: [复兴后]

**Comment by CairoLee** [comment]
收到，初步猜测应该是某个地方溢出了。我找时间分析一下

**Comment by CairoLee** [comment]
由于疾风缓存对 s_skill_db 进行了缓存，而 s_skill_db 中的 delay 字段大小 = MAX_SKILL_LEVEL
因此当你修改 MAX_SKILL_LEVEL 的时候 s_skill_db 中 delay 字段的长度也会变化

疾风缓存在你第一次打开的时候，假定 MAX_SKILL_LEVEL = 10，那么他将在缓存的时候记住了 delay 长度是 10，10个值分别是多少。当你修改了 MAX_SKILL_LEVEL  为 100 之后，下次启动服务端，程序发现 skill_db.yml  的内容并没有变化，因此不会强制缓存过期。

所以程序这时候预期 s_skill_db 中 delay 字段的长度是100，但是缓存文件中 delay 值最大只有 10 个；因此，剩下的 90 个值将会是随机值填充。

————————————

结论：当修改了可能会影响疾风缓存加工的 struct 内容长度的 define 时，请顺手将 db/cache 目录删掉~ 即可解决问题

**Comment by CairoLee** [comment]
此问题已解决，如果还有与其相关的其他情况，可以重新打开此问题
