### ISSUE TITLE
切換地圖的讀取畫面使用ALT+Q或ALT+X開啟裝備欄會導致客戶端崩潰

### ISSUE THREAD

**Issue by VanillaIRV** [PandasWS/Pandas#390]
## 缺陷描述
2019至2021系列登入器在切換地圖的讀取畫面使用ALT+Q或ALT+X開啟裝備欄的快捷鍵會導致客戶端崩潰
實際測試版本:2019-12-24bRagexeRE、2021-01-07aRagexeRE
使用2018-06-20版本登入器則無任何問題
鑑於大部分使用者都已轉為使用2020或2021系列登入器故提出此問題

## 重现步骤
使用2019至2021系列登入器
隨意前往非當前地圖，在讀取畫面時按下ALT+Q或ALT+X

## 预期的正确行为
正常過圖，顯示裝備視窗

## 程序编译模式 (请完善以下信息):

 - 操作系统: Windows 10 x64
 - 编译工具: Visual Studio 2019
 - 代码版本: 1.1.4、1.1.4自編譯
 - 封包版本: 20180620、20210107
 - 工作模式: 复兴后

**Comment by CairoLee** [comment]
听起来有点像是客户端的缺陷，我看看能不能解决
感谢您的反馈~~ 如果有其他的线索或者情报，欢迎继续追加提供

**Comment by CairoLee** [comment]
确认了您所反馈的情况，报错应该是客户端导致的。与服务端应该没有关系～ 思考了一下，可能服务端也没办法绕过这样的缺陷，建议您将这个现象提交给 NEMO。
