### ISSUE TITLE
NPC不會消失以及有影子

### ISSUE THREAD

**Issue by ghost** [PandasWS/Pandas#391]
## 缺陷描述

建立人物後第一個NPC與他說話後  坐起身子   躺在地上的不會消失  有影子
在進入下一張地圖後女角色NPC  說完話應該會不見  結果說完話  依然還在

## 预期的正确行为

1.躺在地上的NPC  回到坐姿狀態  是沒有躺在地上的身子

2.女生的NPC跟他對話完後  應該會消失不見

## 截图

https://drive.google.com/drive/folders/1sqtYQxIKlJFQsLYyjWg9ucn1DOqrNrLe?usp=sharing

圖片放到這網址裡面

## 程序编译模式 (请完善以下信息):

 - 操作系统: Windows 10 x64
 - 编译工具:  Visual Studio 2019 
 - 代码版本: 1.1.4
 - 封包版本: 20200401
 - 工作模式: 复兴后

## 其他附加信息

使用rathena的時候功能正常

**Comment by CairoLee** [comment]
收到，我找时间跟进一下。曾经我遇到过的问题是这个趟在地上的 NPC 会消失…… 到时候一起分析

**Comment by CairoLee** [comment]
结论：这两个现象是光环机制导致的问题，预计将在本周完成修复

**Comment by CairoLee** [comment]
已经合并到 develop 分支，请测试。
此问题已解决，如果还有与其相关的其他情况，可以重新打开此问题
