### ISSUE TITLE
Ubuntu 16.04 運行繁體中文翻譯腳本後開機失敗

### ISSUE THREAD

**Issue by s11005349** [PandasWS/Pandas#394]
## 问题及背景描述
作業系統：Ubuntu 16.04 桌面版
安裝作業系統時，語言選擇繁體中文
（語言並不是指鍵盤input配置，鍵盤我選英文input，再按照
https://blog.xuite.net/yh96301/blog/342227672
新增繁體中文鍵盤input）

克隆熊貓後，按照https://github.com/PandasWS/Pandas/issues/381
此篇執行繁體中文翻譯腳本

之後配置好資料庫（編碼：utf8mb4，collation：default），再運行熊貓，
結果出現多個[Error]，如下
![image](https://user-images.githubusercontent.com/30567162/128586755-a061c5d1-7da1-446f-9d57-318c7c6893aa.png)
![image](https://user-images.githubusercontent.com/30567162/128586772-7ed20b69-e830-4ca2-a6ca-b7b6541cce61.png)
![image](https://user-images.githubusercontent.com/30567162/128586790-34c6672b-6ac5-45e2-b8a2-a357c602f163.png)
![image](https://user-images.githubusercontent.com/30567162/128586809-8cdb36c3-10e5-42c9-9317-aec526223eff.png)
![image](https://user-images.githubusercontent.com/30567162/128586911-e1e65917-2410-4cf9-9ba3-26385f483ba5.png)
最後就卡在下圖畫面，無法正常運行伺服器：
![image](https://user-images.githubusercontent.com/30567162/128586841-2f43f0bb-af0a-4388-a9c8-9d42c8d833a7.png)

附上熊貓產生的crash-dump-file：
[a6cf35fe-89a8-4efa-f9e96589-3d7cf476.dmp.zip](https://github.com/PandasWS/Pandas/files/6948552/a6cf35fe-89a8-4efa-f9e96589-3d7cf476.dmp.zip)

## 做过哪些研究或尝试
1. 按照此篇：
https://samwhelp.github.io/note-ubuntu-18.04/read/howto/install-tool/gedit/
嘗試讓系統辨識big5編碼，問題並沒有解決
2. 以sudo 運行./athena-start start，問題並沒有解決
3. 進入root再執行熊貓，問題並沒有解決
4. 嘗試以相同的資料庫配置（編碼：utf8mb4，collation：default）、執行相同繁體翻譯腳本後，在Windows 10作業系統上是可以正常運行熊貓並進行連線的

## 其他附加信息
報錯截圖已經於文章的"问题及背景描述"小節中附上
crash dump file也已經於文章的"问题及背景描述"小節中附上

**Comment by CairoLee** [comment]
- 关于后半部分的 crash，请使用 GCC-9，应该可以解决
- 关于无法显示繁体中文部分，应该是 translation_tw.yml 中第589 行第 93 列的字符，无法被识别导致错误（方便将 translation_tw.yml 文件发上来吗？）
- 此外，请执行 locale 回车，将显示的信息发出来我看看

**Comment by s11005349** [comment]
1. 后半部分的 crash，使用 GCC-9後已經解決
2. translation_tw.yml 檔案：
[translation_tw.yml.zip](https://github.com/PandasWS/Pandas/files/6953813/translation_tw.yml.zip)
3. locale回車訊息：
![image](https://user-images.githubusercontent.com/30567162/128694918-05c49d5e-7f57-4f22-8251-925017580269.png)

**Comment by CairoLee** [comment]
感谢反馈

关于第一个问题确实存在，我正在解决… 
解决完成会回复此 issue

**Comment by CairoLee** [comment]
哈喽 #398 中的改动已经解决了上面提到的问题，有空请测试哈~ 如果到时候您发现它被 merge 了那就直接拉取 develop 分支做测试

**Comment by CairoLee** [comment]
已经汇入到 master 分支（包含在 1.1.5 版本中发布）

**Comment by s11005349** [comment]
已經測試過了，問題已經解決
謝謝您！
