### ISSUE TITLE
Ubuntu server 20.04.3 编译熊猫模拟器失敗

### ISSUE THREAD

**Issue by s11005349** [PandasWS/Pandas#403]
## 缺陷描述
在Ubuntu server 20.04.3作業系統中
以cmake 3.16.3編譯熊貓失敗
失敗畫面如下圖
![image](https://user-images.githubusercontent.com/30567162/130304966-fbb18750-5880-4cff-a807-5acf0915ac7b.png)

## 重现步骤
1. 安装 git / git-lfs / wget / gcc 编译组件 (gcc 9.3.0)
2. 安装编译 cmake 的所需依赖库 ( openssl )
3. 安装 cmake 3.16.3 (ReadMe中的安裝cmake方法會卡住，因此我直接使用sudo apt install cmake)
    $ sudo apt-get install cmake
    ($ cmake --version 顯示版本為3.16.3)
4. 克隆熊猫模拟器源代码
5. 安装熊猫模拟器的依赖
6. 编译熊猫模拟器自带的 Boost Libraries
    $ cd ~/Pandas/3rdparty/boost/ && bash bootstrap.sh && ./b2
7. 编译熊猫模拟器: 先建立 cbuild 临时目录并进入到目录中
    $ cd ~/Pandas && mkdir cbuild && cd cbuild
8. 生成 makefile 文件
    $ cmake -G "Unix Makefiles" ..
9. 执行编译
    $ make
    即出現失敗畫面如下圖
![image](https://user-images.githubusercontent.com/30567162/130305236-577b2aa3-db10-4df1-9633-27b56a05b84f.png)

## 预期的正确行为
正確、無錯誤編譯熊貓模擬器

## 截图
![image](https://user-images.githubusercontent.com/30567162/130305253-f25dd879-fead-4912-92b0-5a5cc0c5c614.png)

## 程序编译模式 (请完善以下信息):

 - 操作系统: Ubuntu server 20.04.3
 lsb_release -a 的資訊如下圖
 
![image](https://user-images.githubusercontent.com/30567162/130305537-9fc12f59-646d-4869-a81f-59785b40271a.png)

 - 编译工具: GCC 9.3.0
 - 代码版本: 熊貓正式版1.1.5
 - 封包版本: 20200409
 - 工作模式: 复兴后

## 其他附加信息
1. 我有使用imple_translate.py翻譯db，不過不論是否使用python翻譯腳本，編譯皆失敗
    ( 按照腳本ReadMe教學使用'pip install pipenv'會出現'Pipenv: Command Not Found'，
    因此我使用sudo -H pip install -U pipenv解決)
2. $ wget https://github.com/Kitware/CMake/releases/download/v3.16.0-rc1/cmake-3.16.0-rc1.tar.gz \
  && tar -xzvf cmake-3.16.0-rc1.tar.gz \
  && cd cmake-3.16.0-rc1 \
  && ./bootstrap && make -j4 && sudo make install
  若按照ReadMe教學，使用上述指令安裝cmake，過程中 "make -j4" 會卡在59%
  因此我直接使用sudo apt install cmake安裝3.16.3版本
3. locale回車資訊如下圖
![image](https://user-images.githubusercontent.com/30567162/130305479-771a1504-9964-48ed-9858-f563493d385e.png)

**Comment by CairoLee** [comment]
请执行一下 free -m 看一下内存是多少？我猜测有可能是内存不足导致的问题？
否则任何的 gcc 编译报错，都应该给与更详细的错误信息，他这里直接编译过程就结束了

**Comment by s11005349** [comment]
了解，原來是分配內存沒有達到熊貓最小需求的問題

**Comment by CairoLee** [comment]
嗯，曾经我也在 Memory 为 512mb 的 VPS 上被坑过…… 以为是程序出问题，到后面扩大内存就一切正常
