### ISSUE TITLE
合併rAthena官方最新代碼 - 2021年8月9日 後將導致item/item2無法創建中文名稱的道具

### ISSUE THREAD

**Issue by MiherEd** [PandasWS/Pandas#404]
## 缺陷描述
合併rAthena官方最新代碼 - 2021年8月9日 
後將導致item/item2無法輸入中文創建道具
若為英文則正常
## 预期的正确行为
可搜尋中文名稱道具
## 程序编译模式 (请完善以下信息):

 - 操作系统:Windows 10 x64
 - 编译工具:
 - 代码版本: 
 - 封包版本: 20200401
 - 工作模式: 复兴后

**Comment by CairoLee** [comment]
@MiherEd 久等了~
感谢您之前的反馈，此问题确认存在~ 已经提交了相关的 PR 进行修正
如果方便的话，可以测试一下，感谢~

**Comment by CairoLee** [comment]
此问题已解决，如果还有与其相关的其他情况，可以重新打开此问题
