### ISSUE TITLE
web-server 顯示亂碼

### ISSUE THREAD

**Issue by Hong-Shin** [PandasWS/Pandas#433]
## 缺陷描述

黑窗亂碼

## 重现步骤

1. 設置完快捷鍵
2. 登出就看的到了

## 预期的正确行为

顯示中文

## 截图

![image](https://user-images.githubusercontent.com/58548013/134812876-f02e7f96-4afd-42a1-9113-76d21e8dc31c.png)
![image](https://user-images.githubusercontent.com/58548013/134812882-1a90a4c2-6e20-45ba-a92c-981bc01adbcb.png)

## 程序编译模式 (请完善以下信息):

 - 操作系统: Windows 10 x64
 - 编译工具: Visual Studio 2019 社区版
 - 代码版本: 1.1.6
 - 封包版本: 20200902
 - 工作模式: 复兴前

**Comment by CairoLee** [comment]
此问题已解决，如果还有与其相关的其他情况，可以重新打开此问题
