### ISSUE TITLE
能把hercules的這個功能移植到pandas嗎?

### ISSUE THREAD

**Issue by 24msz6eo** [PandasWS/Pandas#439]
https://herc.ws/board/topic/17872-new-hercules-feature-expanded-barter-shop/

**Comment by CairoLee** [comment]
能，计划中~ 如果顺利会在 1.1.7 完成，慢一点会在 1.1.8 完成

**Comment by CairoLee** [comment]
关于 barter shops 的功能，熊猫没有进行自定义实现。而是等到了 rathena 官方来实现，目前已经合并到 develop 分支。当前 rathena 的实现使用起来还不是很灵活，未来会看下怎么拓展。
