### ISSUE TITLE
魅影人孔(SC_MANHOLE)錯誤問題

### ISSUE THREAD

**Issue by king-JI** [PandasWS/Pandas#443]
魅影人孔施放後人物掉落後 應該可以被
瘋狂野草(GN_CRAZYWEED)與地元素領域(SA_LANDPROTECTOR)修除後人員並且起身

## 问题及背景描述

在开始之前, 建议大家先搜索阅读一下"提问的智慧", 学习如何高效提问.
以下是摘抄的一部分关键点, 务必仔细阅读:

1. 提问前, 先自己尝试查找答案
2. 明确表达你的问题及需求
3. 要让问题变得简单易读
4. 问问题的态度应该是以一种讨论的态度
5. 不要过早下结论
6. 直入主题, 切忌因个人情感的过分表达影响的问题的表述
7. 描述问题而不是讲述你的猜测
8. 不要问亲自动手试一下就能知道结论的问题

## 做过哪些研究或尝试

请简明扼要的描述在提问之前您尝试做过的研究, 若有参考链接也请附上.
若没有进行过尝试或者研究, 此处可以写: 无

## 其他附加信息

如果可能的话, 请在此补充与此问题相关的截图或其他一切信息. 若没有
其他附加信息, 可以在这里填写: 无

**Comment by king-JI** [comment]
> 
> 
> 魅影人孔施放後人物掉落後 應該可以被 瘋狂野草(GN_CRAZYWEED)與地元素領域(SA_LANDPROTECTOR)修除後人員並且起身
> ## 问题及背景描述
> 
> 在开始之前, 建议大家先搜索阅读一下"提问的智慧", 学习如何高效提问. 以下是摘抄的一部分关键点, 务必仔细阅读:
> 
>     1. 提问前, 先自己尝试查找答案
> 
>     2. 明确表达你的问题及需求
> 
>     3. 要让问题变得简单易读
> 
>     4. 问问题的态度应该是以一种讨论的态度
> 
>     5. 不要过早下结论
> 
>     6. 直入主题, 切忌因个人情感的过分表达影响的问题的表述
> 
>     7. 描述问题而不是讲述你的猜测
> 
>     8. 不要问亲自动手试一下就能知道结论的问题
> 
> 
> ## 做过哪些研究或尝试
> 
> 请简明扼要的描述在提问之前您尝试做过的研究, 若有参考链接也请附上. 若没有进行过尝试或者研究, 此处可以写: 无
> ## 其他附加信息
> 
> 如果可能的话, 请在此补充与此问题相关的截图或其他一切信息. 若没有 其他附加信息, 可以在这里填写: 无



> 可以在这里填写

參考影片 
https://www.youtube.com/watch?v=WcadB1Eq1k8
0:27秒

**Comment by CairoLee** [comment]
根据分析，当前的样子应该是 rAthena 刻意实现的效果，即：“人孔/黑洞陷阱”被（元素领域/疯狂野草等）解除的时候，只会移除地面上的陷阱，而不会使已经被捕获的玩家立刻脱困。

但您提供的视频确实会立刻脱困，这与 rAthena 的实现是不匹配的。

考虑到这两种情况可能在历史上都出现过，我们判定为这个不是 BUG，但依然添加了一个选项用来控制该行为：新添加的战斗配置选项放在 `conf/battle/pandas.conf` 文件中，选项名称：`remove_manhole_with_status`，具体描述如下：

```
// 当"人孔/黑洞陷阱"地面陷阱被移除的时候, 是否同时使被捕获的玩家立即脱困? [开关选项]
//
// 在 rAthena 默认的设定中, 使用"元素领域"或"疯狂野草"等技能只能解除地面陷阱,
// 但是无法让已经被捕获的玩家立刻脱困.
//
// 但是根据 2018 年 TWRO 的演示视频以及常识,
// 在"人孔/黑洞陷阱"被解除的时候被捕获的玩家应该立刻脱困才正确.
// 因此设立此选项, 方便大家根据自己的需求灵活调整.
//
// 默认值为: yes
remove_manhole_with_status: yes
```

该选项相关代码会被合并到 v1.1.8 版本中，请关注相关动态。

**Comment by CairoLee** [comment]
此问题已解决，如果还有与其相关的其他情况，可以重新打开此问题
