### ISSUE TITLE
寵物光圈無法出現

### ISSUE THREAD

**Issue by Hong-Shin** [PandasWS/Pandas#454]
## 缺陷描述

寵物光圈無法正確出現

## 重现步骤

1. @makeegg 9001 並孵化寵物
2. NPC內添加代碼 unitaura getpetinfo(PETINFO_BLOCKID),1001;
3. 波利抖了一下 甚麼事都沒發生

## 预期的正确行为

出現內建的光環特效

## 程序编译模式 (请完善以下信息):

 - 操作系统: Windows 10 x64
 - 编译工具: Visual Studio 2019 社区版
 - 代码版本: develop 1.1.8
 - 封包版本: 20200902
 - 工作模式: 复兴前

**Comment by CairoLee** [comment]
确认此问题存在，具体什么原因需要定位一下~

**Comment by CairoLee** [comment]
此问题已解决，如果还有与其相关的其他情况，可以重新打开此问题
