### ISSUE TITLE
NPC點了就消失

### ISSUE THREAD

**Issue by 306789** [PandasWS/Pandas#467]
### 缺陷描述

請問 進伺服器點NPC就消失...
不知道是不是在這邊問?

### 重现步骤

躺在地上的NPC 回到坐姿狀態

### 操作系统

Windows

### 工作模式

复兴后 (Renewal)

### 熊猫模拟器版本号

V1.1.8

### 适配的客户端版本

20200401

### 是否为原生缺陷

ra正常

### 备注

[https://github.com/PandasWS/Pandas/issues/391](url)

**Comment by CairoLee** [comment]
收到，我们测试一下，看看是否存在此情况

**Comment by CairoLee** [comment]
确认此问题存在，我们将尽快修正此问题

**Comment by CairoLee** [comment]
已经修正，并发布到 v1.1.9 正式版，请验证

**Comment by 306789** [comment]
可以囉太感謝了！

不過不能使用中文名稱
RA修改char.hpp裡#define TRIM_CHARS 可以用中文名稱
Pandas好像是不用改 但改或不改都不能用中文人物名稱
抱歉語法一竅不通

**Comment by CairoLee** [comment]
> 可以囉太感謝了！
> 
> 
> 
> 不過不能使用中文名稱
> 
> RA修改char.hpp裡#define TRIM_CHARS 可以用中文名稱
> 
> Pandas好像是不用改 但改或不改都不能用中文人物名稱
> 
> 抱歉語法一竅不通

感谢验证。

通常情况下一个问题建立一个issue，因此关于姓名问题建议新开 issue，这样方便跟踪管理。

不过我们这边测试没问题，是否方便新建 issue 并描述您遇到问题的具体角色名？以及数据库编码等等？

**Comment by 306789** [comment]
檢查過結果是資料庫編碼問題 已經可以了

**Comment by CairoLee** [comment]
好的，非常感谢您的反馈~ 
此 issue 的使命结束，先关闭了哟。

如果此问题还有反复，可以重新 open 它。如果有新的问题，请提交新的 issue
