### ISSUE TITLE
instancevar 系列指令在副本實例不存在時將導致地圖伺服器崩潰

### ISSUE THREAD

**Issue by niu0710** [PandasWS/Pandas#471]
### 缺陷描述

```
*setinstancevar(<variable>,<value>,<instance id>);
*getinstancevar(<variable>,<instance id>);
```
在沒有副本實例的狀況下使用將導致地圖伺服器崩潰。

### 重现步骤

1. 不創建任何副本實例
2. 創建 NPC 使用 setinstancevar 或 getinstancevar 並攜帶 <instance_id> 參數且不為 0 或 負值
3. 點擊 NPC, 即地圖伺服器崩潰。

### 预期结果

指令應返回錯誤顯示並阻止地圖伺服器崩潰。
例 : `[錯誤] : buildin_getinstancevar: This Command Only Support at Instance.`

### 操作系统

Windows

### 工作模式

全部 (Both)

### 熊猫模拟器版本号

v1.1.10-dev

### 适配的客户端版本

20211117

### 是否为原生缺陷

是的, 问题依旧

### 备注

    mes "[副本實例崩潰測試]";
	mes "當沒有副本實例時使用以下選項地圖伺服器將崩潰。";
	next;
    switch(select(
		"setinstancevar",
		"getinstancevar"
		))
	{
		case 1:
			setinstancevar('test,1,1);
			break;
		case 2:
			getinstancevar('test,1);
			break;
    }
    end;

**Comment by CairoLee** [comment]
已经修正
