### ISSUE TITLE
疾風緩存未記錄 ap giveap 等參數

### ISSUE THREAD

**Issue by niu0710** [PandasWS/Pandas#472]
### 缺陷描述

依 rAthena 合併 4CrAM 後，疾風緩存未記錄技能 ap 消耗與 giveap 等新數據導致技能異常。

### 重现步骤

1. 在疾風緩存讀取的狀態下，技能需要消耗 ap, 但實際不消耗，技能需要恢復 ap 實際也不恢復等問題。

### 预期结果

技能應該要正常消耗或恢復 ap。

### 操作系统

Windows

### 工作模式

复兴后 (Renewal)

### 熊猫模拟器版本号

v1.1.10-dev

### 适配的客户端版本

20211117

### 是否为原生缺陷

是的, 问题依旧

**Comment by CairoLee** [comment]
已经在 ba3fa16 提交中修正，感谢备忘
