### ISSUE TITLE
关于 script4each 脚本指令的改进需求

### ISSUE THREAD

**Issue by CairoLee** [PandasWS/Pandas#58]
- [x] 使 script4each 的 <脚本> 参数可以忽略最外层的大括号
- [x] 支持 script4eachmob 衍生指令

**Comment by michaelwoooo** [comment]
script4each记得支持NPC::Event
记得别漏了mob

**Comment by CairoLee** [comment]
等待 @michaelwoooo 确认，使用 NPC::EVENT 方式触发的话，其他服务端的行为表现

**Comment by CairoLee** [comment]
关于支持使用 NPC::EVENT 方式来指定要执行的代码，单独开放一个 issues
