### ISSUE TITLE
希望能保持自動點擊必要技能傳統

### ISSUE THREAD

**Issue by mikomike983** [PandasWS/Pandas#694]
### 功能建议或构想

自動點擊技能必要點數
舉例：
天使之擊
習得條件 : 天使之護 3

只點技能天使之擊 天使之護3會自動點好
嘗試修改好幾天都做不出來QQ

### 想实现它的原因

對於技能樹不太熟的人能快速盡情遊玩

### 参考信息

EA

**Comment by 306789** [comment]
之前遇過
後來把台版的
SkillID.lub
skilldescript.lub
skillinfolist.lub
SkillTreeView.lub
反編譯覆蓋過就好了
直接點最後一個技能前面的都幫你點好
不知道是不是一樣的問題

**Comment by mikomike983** [comment]
有 還是不行
謝謝回答

**Comment by CairoLee** [comment]
这个应该是客户端的功能，服务端并不提供类似的机制。请检查客户端的 lua / lub 文件。

请注意：
通常我们会使用 grf editor 或者其他 lub 反编译成 lua 的工具，来对 RO 客户端的 lub 文件进行还原成明文的操作。在大多数情况下，如果这个 lub 文件只有数据（比如 iteminfo）的时候，会工作的很好。但如果这个 lub 文件中包含 function，那么在还原 function 的时候可能会出现异常。

我们建议如果你没有阅读和修改 lua 脚本逻辑的能力，对于 _f.lub 结尾的 lub 文件（通常他们不包含数据），请保持从 KRO 解档出来时候的原始样子，这样可以最大限度避免出现错误
