### ISSUE TITLE
提议：全局单一掉率设置

### ISSUE THREAD

**Issue by michaelwoooo** [PandasWS/Pandas#94]
新增db\item_droprate.txt设置全局单一掉率设置，此掉率无视倍率。

**Comment by michaelwoooo** [comment]
// 全局物品掉率设置，将覆盖倍率
// 数据格式:
// 物品id, 掉率
// 小于1或大于10000的掉率将被忽略
// 举例:
//4140,1 //深渊骑士卡片 - 0.01%

**Comment by michaelwoooo** [comment]
经查找，rA已自带有，位于db/mob_item_ratio.txt
请关闭本提议

**Comment by CairoLee** [comment]
嗯，还真是~ 挺好的~ 关了关了

**Comment by CairoLee** [comment]
重新打开，mob_item_ratio 设置的掉率还会被其他机制影响

**Comment by CairoLee** [comment]
需求已被实现，关闭此问题
